### ISSUE TITLE
BUG: Theme not safe against empty elemets

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/django-dynamic-theme#83]
Theme allows not to have a navbar or media gallery, but they are actually required in the export.

Rewrite the export method to check if they are set or not.

**Comment by HealthyDoggo** [comment]
For this issue, should I just replace non-existent elements with empty strings in the export?

**Comment by HealthyDoggo** [comment]
This issue is solved as above in the pull request, however I have worries that this will mean that an export wiht a bg and no media_gallery will be identical to an export with a bg and no navbar. Could it be better to overhaul the export system and add labels to each element? this would, however, require some changes in other files.
